name: BitcoinPrice
version: '${project.version}'
main: me.martingeltl.bitcoin.BitcoinPrice
api-version: '26.2'
author: Martin Geltl
description: Ein Plugin, das den aktuellen Bitcoin-Preis von der CoinGecko API abruft
website: https://github.com/MartinGeltl21/BitcoinPrice

commands:
  btc:
    description: Zeigt das Hauptmenü oder die aktuellen Einstellungen
    usage: /<command>
  btchelp:
    description: Zeigt Hilfe und erklärt alle Befehle
    usage: /<command>

  btceur:
    description: Zeigt den aktuellen Bitcoin-Preis in Euro
    usage: /<command>
  btcusd:
    description: Zeigt den aktuellen Bitcoin-Preis in US-Dollar
    usage: /<command>
permissions:
  bitcoinprice.admin:
    description: Erlaubt die globale Steuerung der Bitcoin-Preis-Benachrichtigungen
    default: op
